os:
  - linux
  - os x

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python:
        - "3.3"
        - "3.4"
        - "3.5"

    - os: osx
      osx_image: xcode7.2
      python:
        - "2.7"
        - "3.3"
        - "3.4"
        - "3.5"

language: python

addons:
  apt:
    packages:
      - build-essential
      - gdb

install:
  - pip install mock pexpect
  - pip install .

script:
  - mkdir ~/.voltron
  - echo '{"general":{"debug_logging":true}}' >~/.voltron/config
  - nosetests -sv tests/gdb_cli_tests.py
