language: python

matrix:
  include:
    # - os: linux
    #   sudo: required
    #   dist: trusty
    #   python: "3.3"
    # - os: linux
    #   sudo: required
    #   dist: trusty
    #   python: "3.4"
    # - os: linux
    #   sudo: required
    #   dist: trusty
    #   python: "3.5"
    - os: osx
      osx_image: xcode7.2
      language: generic

addons:
  apt:
    packages:
      - build-essential
      - gdb

# install:
#   - pip install mock pexpect
#   - pip install .

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get update -qq ; apt-get install lldb-3.4 ; fi
  - pip install mock pexpect
  - brew install gdb
  - uname -a
  - mkdir ~/.voltron
  - echo '{"general":{"debug_logging":true}}' >~/.voltron/config
  # - nosetests -sv tests/gdb_cli_tests.py
  - sleep 20
